### ISSUE TITLE
Emblems of Triumph from Raid bosses

### ISSUE THREAD

**Issue by Stalker96** [IcecrownServer/Icecrown#10]
Bug: Upon raiding EoE and Naxxramas we have noticed that emblems of triumph have been rewarded (we are aware that dungeons have been fixed to heroism)

Reproduction: Killing any raid boss seems to drop Emblems of triumph

How it should work: Seeing as we are theoretically in patch 3.0.0 we should be getting emblems of Heroism from 10 man raids and Valor from 25 man raids.

Source: http://www.wowhead.com/item=40752/emblem-of-heroism#comments

"This currency can be used to purchase items from vendors found throughout Dalaran, including (but not limited to) Arcanist Ivrenne and Magistrix Lambriesse. Notable items available for purchase with this currency include item level 200 epic-quality gear, item level 200 Savage Gladiator's PVP gear, epic quality gems, and tokens that can be exchanged for Tier 7 chest or gloves. These badges can also be used to purchase Heirloom items from Enchanter Isian, Enchanter Erodin or Brammold Deepmine.

Prior to Patch 3.2, this item dropped from 5-Player Heroic Dungeons and 10-Player Raid Dungeons (with the exception of Ulduar). This currency is no longer available as a drop, but can be purchased at a 1:1 exchange from Arcanist Adurin, Magister Brasael or Usuri Brightcoin in Dalaran for  Emblem of Valor."

**Comment by ThorimDev** [comment]
I cannot confirm this since it was changed, when did you receive the triumph's?

**Comment by ThorimDev** [comment]
Fixed
