### ISSUE TITLE
Monsters instant aggro on spawn

### ISSUE THREAD

**Issue by Naabcakee** [IcecrownServer/Icecrown#102]
there should be about 3-4 second delay before monster aggros you when spawning. Instead  they attack you before we even see them.

**Comment by ThorimDev** [comment]
Can you provide a valid source please?

**Comment by warcraftgeekygamer** [comment]
I agree that there should be a 3 to 4 second delay before mobs aggro upon spawn. On other private servers, mobs do not instantly aggro the nearest player upon spawn - including retail WoW.
