### ISSUE TITLE
Warlock imp have no auto attack and dont seam to lose mana at all.

### ISSUE THREAD

**Issue by Tanesiris** [IcecrownServer/Icecrown#11]
The warlock imp pet seams to cast firebolt with animation correct, On the other hand the imp shouldn´t instant reg the mana back means it always sits on 100% mana after casting firebolt.

This means that the mana should run out sooner or later and the imp should technically stop casting and start auto attacking (melee) as of right now he just stands near the mob doing nothing.

Im also quite sure that the imp shouldn´t start casting firebolt automatically once the pet is in Defensive mode while you right click on a mob from far away.

**Comment by Tanesiris** [comment]
[http://sv.tinypic.com/r/df7qmb/9](url)

**Comment by Tanesiris** [comment]
[IMG]http://i66.tinypic.com/df7qmb.jpg[/IMG]

**Comment by ThorimDev** [comment]
![image](https://cloud.githubusercontent.com/assets/25288671/22284273/d09ec3ac-e2e6-11e6-8b40-1189cb1049b4.png)

**Comment by ThorimDev** [comment]
http://wow.gamepedia.com/Imp_(warlock_minion)

An Imp will also not attack if it is out of mana
