### ISSUE TITLE
Every time I Charge as a Warrior to a mob it makes them levitate 

### ISSUE THREAD

**Issue by leahnie956** [IcecrownServer/Icecrown#113]
![wowscrnshot_021817_131449](https://cloud.githubusercontent.com/assets/25886407/23105925/f4aca9ca-f6ab-11e6-95fb-34d380ca981f.jpg)
![wowscrnshot_021917_135559](https://cloud.githubusercontent.com/assets/25886407/23105926/f4aded08-f6ab-11e6-9d16-be65d4ca73cd.jpg)

**Comment by ThorimDev** [comment]
Doesnt happen all time, will add label on hold for now
