### ISSUE TITLE
Dungeon finder bug

### ISSUE THREAD

**Issue by matejchi** [IcecrownServer/Icecrown#115]
Hello

So the timer for when i can que for another dungeon ran out. After that i still couldnt que, it said one or more members dont meet the requirements for the dungeon, i was queing for RANDOM DUNGEON. I tried reloging and it didnt work. I also wrote a ticket about it.

Thank you

**Comment by icymetal005** [comment]
yep I almost have this bug did the random dungeon finder earlier and when I login I try it again and said one or more members don't meet the requirements..

**Comment by ThorimDev** [comment]
Please clear your Cache files before logging in
