### ISSUE TITLE
Quest: The Chill of Death

### ISSUE THREAD

**Issue by Marcusz87** [IcecrownServer/Icecrown#116]
After a while of killing Vampiric Duskbat's I would be 4/5 Duskbat Pelts, and so the bats stop dropping loot in general. I killed 7 more afterwards and no luck.

**Comment by warcraftgeekygamer** [comment]
That's not a bug. That's RNG and is working as intended. Some mobs have low drop rates, some don't. You just experienced bad luck is all.

**Comment by Marcusz87** [comment]
Weird, after killing 8 nothing dropped at all. I'll try killing more.
