### ISSUE TITLE
Respawn time quest items, like book of Ur

### ISSUE THREAD

**Issue by Odysseus1987** [IcecrownServer/Icecrown#118]
Book of Ur quest in SFK doesnt respawn (or atleast not in 15-20 min) 1 member of the group got it. rest waitied 15 min and then just left cause item didnt come anymore.

Had the same problem with other quest items, blizzlike is 15-20 sec respawn time. Here its 10-15 min .

**Comment by Dreylon** [comment]
+1

**Comment by Odysseus1987** [comment]
Also shipment of Iron (battle for hillsbrad)  respawn timer is 15 min +   while it shouldnt be more then 15 seconds.

**Comment by warcraftgeekygamer** [comment]
#121 
#120

**Comment by ThorimDev** [comment]
respawntime will be fixed next restart.
