### ISSUE TITLE
Npc doesn't work

### ISSUE THREAD

**Issue by Spellforge** [IcecrownServer/Icecrown#123]
Small bug, but bug nonetheless. He won't aggro, I can't attack him. It's like he doesn't exist.

![wowscrnshot_022017_143141](https://cloud.githubusercontent.com/assets/25344461/23134405/02738aa8-f795-11e6-9fbb-c6a9ad22c24b.jpg)

**Comment by ledevrs** [comment]
Fixed. 

Creature tested, and attacking.
