### ISSUE TITLE
Achievement: Giddy Up!

### ISSUE THREAD

**Issue by warcraftgeekygamer** [IcecrownServer/Icecrown#125]
**The Problem**: Upon obtaining level 20 and learning the Apprentice Riding skill, you are not rewarded with the achievement Giddy Up!

**How to Reproduce**:

1. Level Blood Elf to level 20
2. Purchase Apprentice Riding from Perascamin the Riding Trainer
3. Achievement Giddy Up! will not reward you with 10 achievement points

**How it should work**: You should be rewarded 10 achievement points upon purchase of Apprentice Riding skill.

**Source**: http://wow.gamepedia.com/Giddy_Up! and http://wow.gamepedia.com/Perascamin
**Screenshot**: http://pasteboard.co/AUzV7caEO.png

**Comment by ThorimDev** [comment]
Just relog

**Comment by warcraftgeekygamer** [comment]
Interesting. Relog seemed to work. You should also know that I delete my Cache folder every time before I log into the game. Thanks again.
