### ISSUE TITLE
[Minor Issues]

### ISSUE THREAD

**Issue by InsanityN** [IcecrownServer/Icecrown#132]
-on the southern top level of Undercity there are 2 mailboxes in the same place whereas there should be one on the right one on the left;
-in Razorfen Kraul there is a goblin (Willix the importer i think) with a quest which you have to escort him, from the moment the quest begins players are in combat at ALL times, doesn't matter if you are attacked or not, with no mobs around players are in combat;
-binds are changed when you create a new character, it doesn't load the bindings from the 1st configuration. It's actually weird, at least for me, I created 2 new characters and both had their binds changed even the zoom out, default settings which i never touched..was changed. After i go and change the zoom out bind back, 2 other binds from the original binding settings which had already been loaded and were indicating the specific action bar slot was bound to the key i had set, changed to unbound. Hope you understand what I'm saying;
-when I vote I get this:
Access forbidden!

You don't have permission to access the requested object. It is either read-protected or not readable by the server.

If you think this is a server error, please contact the webmaster.
Error 403
icecrown.org
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.5.38 

P.S. I don't really know why but my screenshots don't capture WOW, they capture what's behind WOW, for example I just wanted to screen the mailboxes while typing this and what I captured was the incomplete form of this issue post. I'm not quiet sure if it has something to do with the game but I'm just saying.

**Comment by warcraftgeekygamer** [comment]
> -in Razorfen Kraul there is a goblin (Willix the importer i think) with a quest which you have to escort him, from the moment the quest begins players are in combat at ALL times, doesn't matter if you are attacked or not, with no mobs around players are in combat;

I was in a group today and was able to do this quest without issue. The trick is to let the goblin aggro the mob instead of the player. Only then can you safely kill the mobs as a group.

> -binds are changed when you create a new character, it doesn't load the bindings from the 1st configuration. It's actually weird, at least for me, I created 2 new characters and both had their binds changed even the zoom out, default settings which i never touched..was changed. After i go and change the zoom out bind back, 2 other binds from the original binding settings which had already been loaded and were indicating the specific action bar slot was bound to the key i had set, changed to unbound.

If I am not mistaken, keybinds are client side meaning they are stored on your computer and not the server. Go to your keybind settings and check to make sure it is not set to Character Specific Key Bindings. https://ibb.co/bVO4Ov You may also try to reset to default and re-set your key bindings.

**Comment by InsanityN** [comment]
> If I am not mistaken, keybinds are client side meaning they are stored on your computer and not the server. Go to your keybind settings and check to make sure it is not set to Character Specific Key Bindings. https://ibb.co/bVO4Ov You may also try to reset to default and re-set your key bindings.

Oh yeah, you're right about the binds. Didn't  even see that option.

> I was in a group today and was able to do this quest without issue. The trick is to let the goblin aggro the mob instead of the player. Only then can you safely kill the mobs as a group.

About this now I'm not so sure that it's supposed to work like that, that's what I'm saying.

**Comment by ledevrs** [comment]
Mailbox issue fixed. 

Vote report is invalid. Just tested the entire page and it works. When it disallow you to vote, refresh the vote page, and try again and it will work. 

Bindings are issues related to client side, same as screenshot issue you reported above. 

Quest is working also, just tested that out with regular character, you have to let him aggro the creatures, and you follow. 

Closed issue.
