### ISSUE TITLE
Another broken mob

### ISSUE THREAD

**Issue by Spellforge** [IcecrownServer/Icecrown#135]
This mob doesn't attack, just moves back and forth. If you attack it, it will evade but you will be in combat.

![wowscrnshot_022317_095801](https://cloud.githubusercontent.com/assets/25344461/23257213/25a9edd4-f9c3-11e6-9749-c3a2929b6dbc.jpg)

**Comment by ledevrs** [comment]
Creature fixed. 

Closed.
