### ISSUE TITLE
I've found a new bug while casting.

### ISSUE THREAD

**Issue by Xisksu** [IcecrownServer/Icecrown#137]
Hello!

I am Undead Mage and i found a bug. It's not a serious bug but it is a bug still :D . This thing happens randomly and not everytime. So when i cast my Firebolt my target starts running towards me from my right and suddenly my character model starts turning around at the oposite direction (left). It's not something serious unles my character turns around and my cast stops because the enemy is not infront of me :D .

**Comment by warcraftgeekygamer** [comment]
That is definitely **not** a bug. Your character must always face the mob when casting spells. Which means that when the mob changes direction, so shall you change direction. This is true even in retail WoW. All you need to do is move your character so that he or she is facing the mob at all times.

**Comment by Xisksu** [comment]
But my character rotates it self i mean i was casting and my character started spinning the oposit direction and turned around it self so that the target was behind the character. i didn't do anything

**Comment by warcraftgeekygamer** [comment]
As I mentioned before -- you need to turn your character around so that you are facing the mob. Once you do this, you can continue casting your spells to attack your target.

**Comment by Furieus** [comment]
I think you're missing the point of the post. It has nothing to do with the stop cast when not facing the mob. it has to do with the auto rotation while the player is casting. In retail this does not happen.

**Comment by warcraftgeekygamer** [comment]
Anytime you are casting a spell and are **not** facing a mob, you will **not** be able to cast -- until you have turned your character around. You are also comparing Leigon to WotLK which are two completely different things.

In my leveling time, I have not one time experienced the issue which @Xisksu describes. If this is true, then why hasn't anyone else reported this supposed bug?
