### ISSUE TITLE
Guild Charter bug (minor)

### ISSUE THREAD

**Issue by nathanb1992** [IcecrownServer/Icecrown#138]
when i get signatures from my friends, it doesnt show their names so im unsure how many more i might need, however they say they can see the current signatures on it. My concern is that it wont let me turn it in when I complete the sigs.

**Comment by Freezyicecrown** [comment]
Had this problem too.

**Comment by Freezyicecrown** [comment]
You'll be able to turn it in tho

**Comment by ledevrs** [comment]
Have you tried removing your Cache folder?

**Comment by warcraftgeekygamer** [comment]
As @ledevrs said, I have found that it is generally a good idea to delete the Cache folder.
