### ISSUE TITLE
Heirlooms

### ISSUE THREAD

**Issue by Furieus** [IcecrownServer/Icecrown#14]
Bug: quest window doesn't update the new XP gained with heirlooms. IE: if i have the shoulder/chest/ring on thats 25% XP. If a quest gives me 320 XP the reward should be 400 XP in the quest turn in dialog. When I turn in the quest it gave 405 XP

Source: recalled the experience from retail

Additionally, when you equip the Swift hand of Justice heirloom trinket, it'll do the animation for demon armor I believe. There should be no animation when you put on the trinket.

**Comment by ledevrs** [comment]
Hello.

After checking the report, and doing the same quest without heirlooms, and then doing it again with heirlooms, i can only close this report as invalid. 

Screenshot: http://prntscr.com/ebnsrh
