### ISSUE TITLE
[Monster] Wretched Hooligan - Spawn location in object

### ISSUE THREAD

**Issue by Wabbitface** [IcecrownServer/Icecrown#147]
Minor issue, monster appears to always spawn in the lamp's position which causes line of sight problem for ranged attacks. Additionally the monster cannot move from that position.

**NPC:** http://www.wowhead.com/npc=16162/wretched-hooligan
**Screenshot:** https://i.imgur.com/ZAYNnvI.jpg
**Location on minimap:** http://i.imgur.com/yfwStx9.png

**Comment by ledevrs** [comment]
Fixed.
