### ISSUE TITLE
[Quest] Rathis Tomber's Supplies - Long respawn time

### ISSUE THREAD

**Issue by Wabbitface** [IcecrownServer/Icecrown#148]
Another quest item with unnecessarily long respawn time. Unfair experience for grouped players.
Suggest making quest item respawn immediately.

**Quest**: http://www.wowhead.com/item=22583/rathis-tombers-supplies
**Item:** http://www.wowhead.com/object=181133/rathis-tombers-supplies

**Comment by warcraftgeekygamer** [comment]
@Wabbitface I have already reported this as a bug. Though it is odd because I was under the impression that @ThorimDev fixed the respawn time. See Changelog dated February 19, 2017: http://icecrown.org/changelog

**original report**: https://github.com/IcecrownServer/Icecrown/issues/121

**Comment by Wabbitface** [comment]
@warcraftgeekygamer Yes you might be correct actually, I remembered it being a really bad issue before, not really sure what respawn time it's currently set to. However I hope it's instant like most quests.
