### ISSUE TITLE
Azurelode Mine, hillsbrad foothills

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#156]
Bug: There is a constant hunter Volley inside the mine. Screenshot will explain it better.

How it should work: This volley shouldn't be there.

How to reproduce: Go into Azurelode Mine in hillsbrad foothills, walk all the way to Miner Hackett and check the Volley.

Source: 
![volley](https://cloud.githubusercontent.com/assets/25365123/23343026/362fca50-fc6d-11e6-92ae-6ef8709a77dc.jpg)

**Comment by ledevrs** [comment]
Cannot reproduce.

[Screenshot](http://prntscr.com/edsf9p)
