### ISSUE TITLE
[NPC] Ruga Ragetotem

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#157]
Bug: The NPC Ruga Ragetotem in Camp Taurajo in The Barrens shows a quest when he doesn't have any.

How it should work: The quest doesn't exist OR it's not showing properly

How to reproduce: I don't know if he has a chain before this quest, but check this NPC out for a potential quest.

Source: 
![taurajo](https://cloud.githubusercontent.com/assets/25365123/23343048/90b724c8-fc6d-11e6-92be-f076a2f8724d.jpg)

**Comment by ledevrs** [comment]
He offers no quests, neither there is a sign above him

Make sure you are using a correct game client, with Cache and WTF folders removed before entering out realm.
