### ISSUE TITLE
Felwood quest Corrupted Sabres

### ISSUE THREAD

**Issue by marcus91hh** [IcecrownServer/Icecrown#158]
After u release the saber in the moonwell and bring it back to the quest giver, the quest doesnt complete.

**Comment by warcraftgeekygamer** [comment]
**Quest**: http://wotlk.evowow.com/?quest=4506
**Item**: http://wotlk.evowow.com/?item=12565
**NPC**: http://wotlk.evowow.com/?npc=9996

**Comment by ledevrs** [comment]
Hello.

You should click on the cat, and release it to the Winna.
