### ISSUE TITLE
Hunter pets

### ISSUE THREAD

**Issue by Furieus** [IcecrownServer/Icecrown#16]
Bug: hunter pets seem to be a bit smaller than what they should be when tamed. They also seem to run much slower than the player running. Eventually the pet will despawn as it fell too far behind.

How it should work: With the exception of a few pets (i.e. devilsaurs) the pets should retain the size of the mob they tamed if i recall, and when the player is moving the pet should be able to keep up and not eventually despawn.

**Comment by ThorimDev** [comment]
http://wowwiki.wikia.com/wiki/Hunter_pet
