### ISSUE TITLE
Quest - Howling Fjord - [Sorlof's Booty]

### ISSUE THREAD

**Issue by Scargoth** [IcecrownServer/Icecrown#162]
While on this quest you are suppose to shoot the cannon to kill Sorlof before jumping down and looting. after passing the area 3 times shooting the cannon and not seeing Sorlof, I decided to look for him and see what was up. I realized that he does not come close to the shore like he should till after the boat leaves.
**no screenshots**

**Comment by warcraftgeekygamer** [comment]
**Quest**: http://wotlk.evowow.com/?quest=11529
**NPC Start**: http://wotlk.evowow.com/?npc=24910
**NPC End**: http://wotlk.evowow.com/?npc=24910

**Comment by ledevrs** [comment]
Quest should be fine now. 

Fixed
