### ISSUE TITLE
Falling underground when using flight path

### ISSUE THREAD

**Issue by coka-stefan** [IcecrownServer/Icecrown#171]
This has happened to me at least twice (usually when the game is minimized, not sure if it has something to do with it) and at least once to my friend.

**Comment by ledevrs** [comment]
Hello, which game client are you using?

**Comment by coka-stefan** [comment]
3.3.5 (12340)

**Comment by ledevrs** [comment]
Yes, but are you using our game client, downloaded from www.icecrown.org?

**Comment by coka-stefan** [comment]
No, I'm using a client I've had for a long time on my computer, but I've never had this kind of thing happen on other servers

**Comment by ledevrs** [comment]
Try downloading the client that is linked on our website. This issue is only happening to you at the moment.
