### ISSUE TITLE
[Quest] [NPC] Leave No One Behind (Zul'Drak)

### ISSUE THREAD

**Issue by kingkrule** [IcecrownServer/Icecrown#175]
http://www.wowhead.com/quest=12512/leave-no-one-behind

https://www.youtube.com/watch?v=lLOpUvAxjw0 - Video of quest, Bug not included

In this quest, you are supposed to use Quest Item: Crusader's Bandage to begin a short escort with 3 NPCs, 2 of the 3 NPCs worked, but the third NPC, Crusader Josephine, didn't react to my using the Crusader's Bandage on her, after logging out, and restarting client, she still did not react to the Crusader's Bandage.

**Comment by ledevrs** [comment]
Hello.

Tested all creatures, everything is working as intended. 
Please remove your CACHE/WDB folder before reporting and redoing the quest.

**Comment by AngryEsztike** [comment]
i escort the npcs, but i dont get credit...they are just folowing me forever in zuldrak
