### ISSUE TITLE
Horne of the Ancient Mariner- quest

### ISSUE THREAD

**Issue by Nosferatur** [IcecrownServer/Icecrown#177]
http://www.wowhead.com/quest=11660/horn-of-the-ancient-mariner

The quest item drops from Kvaldir Mistweavers but it doesnt happened even after 20 min farming those mobs. Guess this quest is bugged on some way or drop chance isnt as intended
Ty best regards

**Comment by ledevrs** [comment]
Hello.

After testing the quest i can only label it as invalid. 
Received the quest item on my third creature.
