### ISSUE TITLE
SOPHOSTRA human mage HACKER

### ISSUE THREAD

**Issue by gorkael** [IcecrownServer/Icecrown#191]
player Using a hacker I was chasing him and when he arrived on a mountain he could not climb he jumped and appeared on the mountain thus dodging from me. Until he jumped and fell and I killed, I think this is Hacker and there are no wizard skills. I think it's good to find out
![whatsapp image 2017-03-06 at 21 41 47](https://cloud.githubusercontent.com/assets/25286757/23637984/bd4a19b8-02bd-11e7-9e0d-b0196aee3de1.jpeg)

**Comment by masterfluffy1234** [comment]
the best method for this is not posting this on the bugtracker but just be silent and write a gm to observe him a while :D when hes hacking then he will get banned. But now he prob will never do it again cause u made it public^^

**Comment by gorkael** [comment]
I searched for one and I did not find it, I do not care, at least his name is dirty for anyone to see, and who knows, take shame and stop using hacker
