### ISSUE TITLE
[Naxx 25m] Bosses just dropping 1x T7,5 Token instead of 2x 

### ISSUE THREAD

**Issue by masterfluffy1234** [IcecrownServer/Icecrown#197]
While clearing Naxx 25m, we noticed that all the Bosses except Gluth and KT just dropped 1x T7,5 Token. 
The Bosses are: Loatheb, Four Horseman, Thaddius.

**Comment by ledevrs** [comment]
Hello.

The drop chance of each token is high, and goes around 50-60%, and that is blizzlike. Please provide us a source where it says two tokens should drop, and reopen the issue.
