### ISSUE TITLE
Halls of Lightning

### ISSUE THREAD

**Issue by Oltean2** [IcecrownServer/Icecrown#3]
yesterday we ran a quick HoL using the dungeon finder, which works! in HoL we encountered a few bugs, first was the gauntlet. the armor debuff is susposed to stack but does not. second bug was volkhan (second boss). he is susposed to smash his golems when he runs back to the smith to create more but he does not, instead he just spams it alot faster than retail and makes alot of golems. lol third issue was Ionar, when he turns into sparks and chases you, he only turns into 2 sparks chasing 2 of the players we noticed, which is not retail, in retail i think it was a spark per player or 4 sparks and 1 player didnt have one. anyway last but not least, fourth issue. this issue was pretty sad because it made things alot harder in the dungeon. the hallway where the statues turn into fightable mobs was a little bugged, its susposed to be 3-4 mobs will spawn per section you cross. instead its more like 7-8 and its extremely difficult to pass this part because of the fears...

**Comment by ThorimDev** [comment]
https://github.com/IcecrownServer/Icecrown/blob/master/README.md
