### ISSUE TITLE
 [It Could Be Anywhere!]

### ISSUE THREAD

**Issue by Byqvist** [IcecrownServer/Icecrown#39]
Dont know if this is a actual bug or not but it took me 1.5 hours of killing to get the drop of the Golden Engagement Ring. Either im very unlyck or you might wana increase the droprate just a little bit =)

**Comment by bongobg** [comment]
Hi!

Check [the drop rate](http://wotlk.evowow.com/?item=38642#dropped-by:0-8+1) - most of the NPCs has 1% so it's pretty accurate to grind 1,5h.
