### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Slackbag** [IcecrownServer/Icecrown#42]
By spamming right click your character will start auto attack at an insane rate. Its only visual tho, not a major bug

**Comment by ThorimDev** [comment]
Cannot reproduce, please clear your WDB folder and reopen the issue if it still happens.

**Comment by Furieus** [comment]
I know this is closed, however, my cache and what not is clear and I experienced the same thing..

**Comment by Slackbag** [comment]
https://gyazo.com/70d6d08fea34890e855f5901cac36563
