### ISSUE TITLE
[Naxxramas] Sapphiron Spawn animation

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#51]
Bug: Sapphiron's spawn animation isn't working, he just insta spawns (naxxramas 25, didnt test on 10 man)

How to reproduce: go into naxx 25 and come close to sapphiron's spawn location, wait for a bit and he will insta spawn with no animation

How it should work: Sapphiron has an animation before spawning where he assembles himself from bones on the ground

Source: https://www.youtube.com/watch?v=prvKHL4b2e8

**Comment by ThorimDev** [comment]
![image](https://cloud.githubusercontent.com/assets/25288671/22487777/0a69a8cc-e80f-11e6-9c98-eda4e78c1396.png)
