### ISSUE TITLE
Army of the dead aggro

### ISSUE THREAD

**Issue by Chiws** [IcecrownServer/Icecrown#56]
Bug: Army of the Dead attacks when player stays idle. In fact aggro range is very large.

How to reproduce: Stand near mobs, but don't get their aggro, cast Army of the Dead.

How it should work: Army of the Dead shouldn't attack mobs, not targeted by player.

![army of the dead](https://cloud.githubusercontent.com/assets/25467555/22486530/1704c60c-e80a-11e6-80c4-6d1503c2c7ff.jpg)

**Comment by ThorimDev** [comment]
Source?

**Comment by SASzou** [comment]
This source from wowhead states that this is not a bug:
![screenshot_20170201-023745](https://cloud.githubusercontent.com/assets/25365123/22490830/1a39d72c-e828-11e6-9f72-dd4a9ab29d5b.png)
No offense to you Chiws
