### ISSUE TITLE
Bloodworms aggro

### ISSUE THREAD

**Issue by Chiws** [IcecrownServer/Icecrown#57]
Bug: Bloodworms attacks enemies when player stays idle.

How to reproduce:
-Buy Bloodworms talent in Blood spec
-Attack single enemy, after killing it stay idle

How it should work:
Bloodworms should not attacks targets not attacked by player.

![bloodworms](https://cloud.githubusercontent.com/assets/25467555/22486599/6e80ae32-e80a-11e6-8fd4-1ff0112f3393.jpg)

**Comment by ThorimDev** [comment]
Source?

**Comment by SASzou** [comment]
This source from wowhead states that this is not a bug:
![screenshot_20170201-023745](https://cloud.githubusercontent.com/assets/25365123/22490775/c9de3142-e827-11e6-948d-9a99b1152e22.png)
No offense to you Chiws
