### ISSUE TITLE
Auto attack visual bug

### ISSUE THREAD

**Issue by Slackbag** [IcecrownServer/Icecrown#61]
Sorry for wrong format before. Created a GIF to clarify the issue. 
https://gyazo.com/70d6d08fea34890e855f5901cac36563

Bug; Characters appear to auto attack at an unintended fast rate. Sorry for wrong format before. Created a GIF to clarify the issue. 

How to reproduce the bug; Spam clicking right mouse button

How it should work; There should be no visual change if players spam click a target

Source: Honestly no idea

**Comment by ThorimDev** [comment]
Client issue
