### ISSUE TITLE
NPC/Quest Lazy Peons

### ISSUE THREAD

**Issue by Furieus** [IcecrownServer/Icecrown#62]
Bug: most of the lazy peons in the orc/troll starting area are just standing there idle

What should happen: Lazy peons should periodically Chopping at trees and dropping off the lumber at wood piles that are near the trees. Every so often some of them should 'take a nap' in doing so this allows players to complete the quest 'Lazy Peons'

How to reproduce: This is nothing a player can reproduce, just bring a character to orc/troll starting zone and watch all the lazy peons scattered about.

Source: http://wotlk.openwow.com/quest=5441

Note: Some of them do take a nap, but seems to take forever. Can't recall the timer on retail, but it might take forever to complete if a bunch of players are at the orc starting zone. When you do wake them up with the blackjack, they run to the collected wood pile and start chopping there with no axe in their hand. They should run to the tree and chop for a bit before bringing wood to the pile.

**Comment by ThorimDev** [comment]
Cannot reproduce
