### ISSUE TITLE
The Drakkensryd

### ISSUE THREAD

**Issue by Spellforge** [IcecrownServer/Icecrown#63]
Quest works. Jumping from one drake to another is good. But once you finish and grapple yourself to a lamp to get off you get stuck. Once you are stuck you can't do anything but to relog to fix the issue. But sometimes when you relog you might spawn mid air and fall to your death,
![wowscrnshot_020117_172638](https://cloud.githubusercontent.com/assets/25344461/22515951/936527a6-e8a4-11e6-9021-0b65763429d6.jpg)

**Comment by bongobg** [comment]
Hi, that's not true. I did the quest yesterday and after you pull yourself to the lamp you have the red arrow button for unmounting down left. After you unmount you receive a parachute and drop to the ground. I do not know how it works in retail but it looks pretty good to me - no need to relog.

**Comment by Spellforge** [comment]
I must have missed that then. I'll close it then,.
