### ISSUE TITLE
Mangy nightsaber skinning bug/abuse

### ISSUE THREAD

**Issue by Stalker96** [IcecrownServer/Icecrown#7]
Bug: Skinning the mangy nightsabers in Teldrassil will often reward you with a *medium leather* or a *medium hide*

Reproduction: Skin it ;)

How it should work: A level 2 NPC like a Mangy nightsaber should *mostly* drop *ruined leather scraps* or *light leather* if you are lucky.

source: http://www.wowhead.com/npc=2032/mangy-nightsaber#skinning

**Comment by ThorimDev** [comment]
Fixed, thanks
