### ISSUE TITLE
NPC's 'falling' to levels beneath them

### ISSUE THREAD

**Issue by Stalker96** [IcecrownServer/Icecrown#72]
Bug: NPCs in the world tend to fall to a level(cave or underground) beneath them.
I reported this originally about the kurzen compound, it was fixed (I have not checked myself). However, I have still seen this bug in other places, for example: the wolves/spiders in duskwood that are "above" the cave beneath raven hill cemetery. 
example 2: the spiders that are above fargodeep mine in elwynn forest
example 3(NOT CHECKED): I have not checked this but I believe that the spiders/NPCs in searing gorge would probably 'fall' to the mine beneath the surface.

How to reproduce: Venture into these mines, you shall see NPCs that are meant to be on the earth's surface are actually inside caves(underground level)

how it should work: these NPCs should not be in the lower level

Source: knowledge and logic
![wowscrnshot_020317_122458](https://cloud.githubusercontent.com/assets/25317037/22588026/c3eca8fe-ea0c-11e6-817f-d55e59d95e74.jpg)

NOTE: I am reporting this as a general bug, not a bug SPECIFIC to darkshire and fargodeep mine, as almost every "mine" (area with an underground level) has this bug, I believe a fix should rather be implemented to the entire server than to fix these specific areas (like is the case with the 'already' fixed kurzen compound)

**Comment by bongobg** [comment]
I saw that yesterday in Dragonblight so I confirm this indeed happens. The NPC fell through the snow just in front of me.
