### ISSUE TITLE
Lost Shandaral Spirit / Grove Walker

### ISSUE THREAD

**Issue by Byqvist** [IcecrownServer/Icecrown#75]
Lost Shandral Spirit/Grove Walker in Crystalsong Forest cast Regrowth/rejuvenation on players.
The should cast these healing spells on themself once they get below 40-50ish %.

**Comment by ThorimDev** [comment]
![image](https://cloud.githubusercontent.com/assets/25288671/23362899/2dc609de-fcf8-11e6-96f6-0277ddc68750.png)
