### ISSUE TITLE
[Wintergrasp]

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#76]
Bug: The text that appears when the Horde captures Wintergrasp is incorrect. (Alliance should be tested)

How to reproduce: Capture wintergrasp fortress as a horde player and the text that appears is The Alliance has captured WG

how it should work: should show The Horde has captured WG

Source: 
![wowscrnshot_020417_223741](https://cloud.githubusercontent.com/assets/25365123/22628191/64137dea-ebd8-11e6-94a8-2cac106f3a7f.jpg)

**Comment by Jorderon** [comment]
seems to be connected to this issue:
https://github.com/IcecrownServer/Icecrown/issues/64
