### ISSUE TITLE
Charge pathing --> hole in the ground

### ISSUE THREAD

**Issue by Jorderon** [IcecrownServer/Icecrown#8]
Hi,

I refer to the charge pathing video, I saw on the Icecrown Homepage.

In Storm Peaks / Sifreldar my Worrior fell trough a "hole in the ground" as I know it from other private servers. Due to the charge pathing video, I wonder if this should still be possible on Icecrown. 

The way it happend and the way it should be is explained in the picture attached. Also the exact position and view direction I marked there.

<a href="http://www.fotos-hochladen.net/view/20170124170lck0hei81d.png" target="_blank"><img src="http://www.fotos-hochladen.net/thumbnail/20170124170lck0hei81d_thumb.jpg" border="0"></a>

Would be happy about a feedback if this is a bug in your eyes. Otherwise I post all the "holes" I find on my way... ;-)

Have fun

J

**Comment by ThorimDev** [comment]
Does this happen on other spots aswell?

**Comment by Jorderon** [comment]
Since I was playing warrior only short in the beta yet, I found only this one so far. But I know this problem from other private servers. Most of the times I the Warrior charges upward hills or slopes, even in BGs. 
Would really love to try the positions I know in Warsong and Alterac Valley. Unfortunately BGs don't open, due to the small population. 
If it's okay for you, I charge around the world and post the positions I find under this thread. 

Nice evening 

J
