### ISSUE TITLE
[Naxxramas] Gluth 10m

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#82]
Bug: Gluth will occasionally lose his aggro from the tank and go to one of the kited zombies to heal 5% of hit hp.

How to reproduce: go to Gluth in Naxxramas, tank him against the door and kite the zombies on the other  side of the room, watch him sometimes leave the main tank to go consume a zombie and heal himself.

How it should work: Gluth shouldn't be losing the tank's aggro to go heal himself, he should just stay where he is being tanked

Source: https://www.youtube.com/watch?v=sukPVOnR8U0 Gluth encounter from a kiting hunter's perspective

**Comment by ThorimDev** [comment]
Cannot reproduce, tested for 30mins+
