### ISSUE TITLE
[Naxxramas] Noth the plaguebringer 10m

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#83]
Bug: In phase 2 where Noth becomes invulnerable and sends waves of adds against the raid, he stays on the ground (invulnerable) while he should teleport to a balcony. Currently he becomes invulnerable while staying on the ground.

How to reproduce: run Noth the plaguebringer and reach phase 2 then check it out

How it should work: Noth shouldn't stay on the ground and instead should teleport to a balcony, where he becomes invulnerable.

Source: from wowiki: Every 110 seconds of combat Noth will teleport away to a balcony and become invulnerable while waves of skeletons attack the raid.
http://wowwiki.wikia.com/wiki/Noth_the_Plaguebringer

**Comment by ThorimDev** [comment]
Fixed
