### ISSUE TITLE
Serious RDF bug

### ISSUE THREAD

**Issue by SASzou** [IcecrownServer/Icecrown#85]
Bug: When an RDF ends, all the people in the party usually leave the group. It all turns down to the last 2 people that were left in the group: between those 2, the guy that clicked Leave Group from his portrait leaves the group normally, and the other guy gets stuck in an invisible party and gets assigned the position of Dungeon Guide while there is no one partied with him. This leads to the character being stuck forever in RDF. Relogging doesn't help.

How to reproduce: run a 5 man RDF, get it done, everyone leave and watch what happens to the last guy that supposedly becomes alone because all 4 members have left the party.

How it should work: When the last 2 guys are in the party, if one of them clicks leave group, both should be freed of the party...

Here are some screenshots that happened on my rogue and pally, Rogue has been like this for the past 2 hours:
![wowscrnshot_020717_193020](https://cloud.githubusercontent.com/assets/25365123/22703575/499d96f8-ed6d-11e6-9420-f009d24cd15a.jpg)

![wowscrnshot_020717_193135](https://cloud.githubusercontent.com/assets/25365123/22703529/2442c78e-ed6d-11e6-8da8-6b985cdd045d.jpg)

**Comment by SASzou** [comment]
Note: this is an occasional bug, might be hard to reproduce it, and writing /run LeaveParty() works to solve it

**Comment by Harlene92** [comment]
Relog helps too

**Comment by ThorimDev** [comment]
Please remove your cache files before loggin in.
