### ISSUE TITLE
wintergrasp: quest giver without Quest

### ISSUE THREAD

**Issue by Jorderon** [IcecrownServer/Icecrown#90]
**Bug:**
Officer Ahbramis in Wintergrasp has this yellow "!" above his head, but no Quest left.
It seem to be the "!" from the Quest you can only get, when you hold wintergrasp, called "southern sabotage".

**There shoult be** no yellow "!" above the head of a quest giver without a quest available.

**To be reproduced** if the Horde holds wintergrasp. go to the Alliance Camp (flightpoint) and find "Ahbramis". See the yellow "!" above his head. Rightklick on Ahbramis. Accept all the quests available. "untarget" Ahbramis and see the yellow "!" still there. ;-)

**Source** is the general logic.

<a href="http://www.fotos-hochladen.net/view/20170126034fevm95lp6w.png" target="_blank"><img src="http://img5.fotos-hochladen.net/thumbnail/20170126034fevm95lp6w_thumb.jpg" border="0"></a>

**Comment by ThorimDev** [comment]
Invalid, please clear your cache.

![image](https://cloud.githubusercontent.com/assets/25288671/23092610/dcb9d316-f5ce-11e6-8859-16650b40053f.png)

**Comment by Jorderon** [comment]
Read the text under reproduced, so you see that it's not invalid
